---

# todo: check if bug that debian reset's to dhcp before after-config-reboot is a role-issue

- name: Network | Debian | Configuring startup-service
  ansible.builtin.import_tasks: startup.yml
  when: NW.startup_service.enable
  tags: [routing, interfaces]

- name: Network | Debian | Configuring network interfaces
  ansible.builtin.import_tasks: interfaces.yml
  tags: interfaces
  when:
    - NW.interfaces is defined
    - NW.interfaces | length > 0

- name: Network | Debian | Applying network config via verifier
  ansible.builtin.import_tasks: verification.yml
  when: NW.verification.enable
  tags: [routing, interfaces, base]

- name: Network | Debian | Applying network config w/o verification
  ansible.builtin.import_tasks: apply.yml
  when: not NW.verification.enable
  tags: [routing, interfaces, base]
