---

- name: Network | Debian | Startup | Creating script directory
  ansible.builtin.file:
    path: "{{ network_script_dir }}"
    owner: 'root'
    group: 'root'
    state: directory
    mode: 0755

- name: Network | Debian | Startup | Copying scripts
  ansible.builtin.template:
    src: "templates/usr/local/sbin/ansibleguy.base-network/startup.sh.j2"
    dest: "{{ network_script_dir }}/{{ startup_script }}"
    owner: 'root'
    group: 'root'
    mode: 0755

- name: Network | Debian | Startup | Copying service
  ansible.builtin.template:
    src: 'templates/etc/systemd/system/ansibleguy.base-network.startup.service.j2'
    dest: "/etc/systemd/system/{{ startup_service }}"
    owner: 'root'
    group: 'root'
    mode: 0644

- name: Network | Debian | Startup | Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Network | Debian | Startup | Enabling service
  ansible.builtin.systemd:
    name: "{{ startup_service }}"
    enabled: true